/*  ------------------------------------------------------
     Routine name:  my_diagram
     Description:   
     Project file:  Задержка автомат.prt

------------------------------------------------------  */

int i;
int j;
int c;
ret = 0;
memcpy(&input_0,&input_0_default,sizeof(input_0_default));
memcpy(&out_0,&out_0_default,sizeof(out_0_default));
memcpy(&state_vars->my_diagramv0_out_0_,&my_diagramv0_out_0_default,sizeof(my_diagramv0_out_0_default));
memcpy(&state_vars->my_diagramv1_out_0_,&my_diagramv1_out_0_default,sizeof(my_diagramv1_out_0_default));
delay_init(&engine);
