/*  ------------------------------------------------------
     Routine name:  my_diagram
     Description:   
     Project file:  Задержка автомат.prt

------------------------------------------------------  */

/*       Local stack variables                */
int i;
int j;
int c;
int itmp1;
int itmp2;
int itmp3;
double tmp1;
double tmp2;
double tmp3;
double tmp4;
double tmp5;
double tmp6;
double tmp7;
char f;
char tmp_f_1;
char u_s;
char u_r;
symbol = (enum DelayInputSymbol)state_vars->my_diagramv0_out_0_;
output = delay_engine(&engine, symbol);
state_vars->my_diagramv1_out_0_ = output;
ret = 0;

