Document: mydebian
Title: Debian mydebian Manual
Author: <insert document author here>
Abstract: This manual describes what mydebian is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/mydebian/mydebian.sgml.gz

Format: postscript
Files: /usr/share/doc/mydebian/mydebian.ps.gz

Format: text
Files: /usr/share/doc/mydebian/mydebian.text.gz

Format: HTML
Index: /usr/share/doc/mydebian/html/index.html
Files: /usr/share/doc/mydebian/html/*.html
